# Generated by Django 5.2.13 on 2026-05-07 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('resume_mismatch_flag', models.BooleanField(default=False)),
                ('pdf_s3_url', models.URLField(blank=True, max_length=500)),
                ('is_visible_to_candidate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='interviews.interview')),
            ],
        ),
    ]
