# Generated by Django 5.2.13 on 2026-05-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='overall_summary',
            field=models.TextField(blank=True),
        ),
    ]
