# Generated by Django 5.2.13 on 2026-05-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_overall_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='overall_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
