import React from 'react';
import { Navigate, Outlet } from 'react-router-dom';

const ProtectedRoute = () => {
  // Check for the session token generated by the magic link
  const token = localStorage.getItem('candidate_token');
  const isAuthorized = !!token; 

  if (!isAuthorized) {
    // If no token, we can't let them in. 
    // Since login is removed, we show they need an invitation.
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 p-4">
        <div className="text-center space-y-4">
          <div className="w-16 h-16 bg-amber-100 text-amber-600 rounded-full flex items-center justify-center mx-auto">
            <span className="material-symbols-outlined text-3xl">mail</span>
          </div>
          <h1 className="text-xl font-bold text-gray-900">Invitation Required</h1>
          <p className="text-gray-500 max-w-xs">Please use the unique interview link sent to your email to access this portal.</p>
        </div>
      </div>
    );
  }

  return <Outlet />;
};

export default ProtectedRoute;
