# Generated by Django 4.2.30 on 2026-05-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interview',
            name='experience',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
