# Generated by Django 5.2.13 on 2026-05-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='ats_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
