# Generated by Django 6.0.4 on 2026-05-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interview_education_interview_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='education',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='experience',
        ),
    ]
