# Generated by Django 5.2.13 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interview_ats_score_interview_candidate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
