# Generated by Django 6.0.4 on 2026-05-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_candidate_name_restore'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
