# Generated by Django 5.2.13 on 2026-05-14 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_interview_resume_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_email', models.EmailField(max_length=254)),
                ('overall_experience', models.IntegerField(blank=True, null=True)),
                ('ai_clarity', models.IntegerField(blank=True, null=True)),
                ('ease_of_use', models.IntegerField(blank=True, null=True)),
                ('technical_stability', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='interviews.interview')),
            ],
        ),
    ]
