# Generated by Django 5.2.13 on 2026-05-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_candidatereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='round_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('hr', 'HR')], default='technical', max_length=20),
        ),
    ]
