# Generated by Django 5.2.13 on 2026-05-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_interview_overall_score_interview_round_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='round_type',
        ),
    ]
