# Generated by Django 4.2.30 on 2026-04-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_jobapplication_remove_job_recruiter_delete_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='jd_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='jd_file',
            field=models.FileField(blank=True, null=True, upload_to='jds/'),
        ),
    ]
