# Generated by Django 5.2.13 on 2026-05-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=255, unique=True)),
                ('call_count', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('max_calls', models.IntegerField(default=50)),
                ('max_tokens', models.IntegerField(default=100000)),
                ('last_call_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('round_type', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('hr', 'HR'), ('screening', 'Screening'), ('evaluation', 'Evaluation')], max_length=20)),
                ('system_instruction', models.TextField(help_text='The system instruction/prompt for this round.')),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('round_type', 'version')},
            },
        ),
    ]
