# Generated by Django 5.2.13 on 2026-05-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromptTemplate',
        ),
        migrations.DeleteModel(
            name='SessionQuota',
        ),
    ]
